%YAML:1.0

cam0:
# IMPORTANT, after transforming from the IMU link to the camera bse (ROS convention), you need to transform to camera optical link (ROS convention)  
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [  0.0000, -0.1736,  0.9848, 0.20 ]
    - [ -1.0000,  0.0000,  0.0000, 0.00 ]
    - [  0.0000, -0.9848, -0.1736, 0.10 ]
    - [  0.0000,  0.0000,  0.0000, 1.00 ]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.25, 0.12, -0.00028, 0.00005]
  distortion_model: radtan
  intrinsics: [317.21, 317.21, 376.0, 240.0]
  resolution: [752, 480]
  rostopic: "/target/camera"