%YAML:1.0

cam0:
# Extrinsics that match the TF static transforms in the launch file
# In the launch file: [0.10, -0.05, 0.0, 1.57079632679, 0, 1.57079632679]
# Converting to T_imu_cam (camera in IMU frame)
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [  0.0000,  0.0000,  1.0000, 0.10 ]
    - [ -1.0000,  0.0000,  0.0000, -0.05 ]
    - [  0.0000, -1.0000,  0.0000, 0.00 ]
    - [  0.0000,  0.0000,  0.0000, 1.00 ]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [450.0, 450.0, 376.0, 240.0]
  resolution: [752, 480]
  rostopic: "/target/stereo/left/image_raw"
  timeshift_cam_imu: 0.0  # Timeshift between camera and IMU

cam1:
# Extrinsics that match the TF static transforms in the launch file
# In the launch file: [0.10, 0.05, 0.0, 1.57079632679, 0, 1.57079632679]
# Converting to T_imu_cam (camera in IMU frame)
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [  0.0000,  0.0000,  1.0000, 0.10 ]
    - [ -1.0000,  0.0000,  0.0000, 0.05 ]
    - [  0.0000, -1.0000,  0.0000, 0.00 ]
    - [  0.0000,  0.0000,  0.0000, 1.00 ]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: radtan
  intrinsics: [450.0, 450.0, 376.0, 240.0]
  resolution: [752, 480]
  rostopic: "/target/stereo/right/image_raw"
  timeshift_cam_imu: 0.0  # Timeshift between camera and IMU