%YAML:1.0 # need to specify the file type at the top!

lidar:
  enabled: true
  max_n: 1
  do_calib_dt: false
  do_calib_ext: true
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-6
  init_cov_ex_p: 1e-6
  max_range: 300.0
  min_range: 0.5
  chi2_mult: 1
  raw_do_downsample: true
  raw_downsample_size: 0.3
  raw_noise: 0.01
  raw_remove_motion_blur: false
  raw_point_dt: 1e-6
  map_do_downsample: true
  map_downsample_size: 0.3
  map_noise: 0.01
  map_ngbr_num: 15
  map_ngbr_max_d: 15.0
  map_decay_time: 120
  map_decay_dist: 100
  map_use_icp: true
  map_icp_dist: 50
  plane_max_p2pd: 0.2
  plane_max_condi: 300.0

lidar0:
  timeoffset: 0.0
  T_imu_lidar:
    - [0.0, -1.0, 0.0, 0.0]
    - [0.0, 0.0, -1.0, 0.0]
    - [1.0, 0.0, 0.0, 0.12]
    - [0.0, 0.0, 0.0, 1.0]
  topic: "/lidar/points"