%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 2.0e-3  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias: 3.0e-3   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise: 1.6e-4     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias: 1.9e-5       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: "/target/mavros/imu/data_raw"
  